version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/html 
    ports:
      - "80:80"            
    depends_on:
      - db
      
  db:
    image: mariadb:10.5
    environment:
      MYSQL_ROOT_PASSWORD: SW-3Year
      MYSQL_DATABASE: publication_db 
      MYSQL_USER: Pup_addmin                     
      MYSQL_PASSWORD: Puplication5             
    volumes:
      - db_data:/var/lib/mysql 

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db                    
      MYSQL_ROOT_PASSWORD: SW-3Year
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  db_data: